site_name: aws! security blog
site_url: https://sjiminar.github.io
theme:
  name: material
  logo: assets/images/logo.png
  features:
    - content.action.edit
  palette: 
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  extra_css:
    - css/custom.css

plugins:
  - search
  - social
  - meta
  - blog:
      blog_dir: blog/posts
      show_post_date: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Blog: blog/index.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sjnar/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/RYwhuSXx
    

  blog:
    post_date_format: '%Y-%m-%d'

site_dir: site
