site_name: aws security blog
site_url: https://sjiminar.github.io
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - social

nav:
  - Home: index.md
  - Blog: blog/index.md

site_dir: site
