site_name: aws! security blog
site_url: https://sjimnar.github.io/
site_description: A blog about AWS security
site_author: Sergio Jimenez
repo_url: https://github.com/sjimnar
theme:
  name: material
  logo: assets/images/logo.png
  features:
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - navigation.footer
  
  palette: 
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  extra_css:
    - css/custom.css

plugins:
  - search
  - social
  - meta
  - awesome-pages
  - blog:
      blog_dir: blog/


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - tables
  - meta
  - abbr
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true 

nav:
  - Home: index.md
  - Blog:
      - IAM Access Analyzer - A Cloud Guardian for Your S3 Buckets: blog/posts/s3-iam-access-analyzer.md
      - S3 Ransom Anatomy: blog/posts/s3-ransom-anatomy.md
      - S3 Ransomware Batch Deletion: blog/posts/s3-ransomware-batch-deletion.md
  - About: about.md

copyright: Copyright &copy; 2025 Sergio Jimenez. All rights reserved.


extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sjnar/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/RYwhuSXx
  analytics: 
    provider: google
    property: 'G-Q0J7C5E72G'
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! 

  blog:
    post_date_format: '%Y-%m-%d'