site_name: aws! security blog
site_url: https://sjimnar.github.io/
site_description: A blog about AWS security
site_author: Sergio Jimenez
repo_url: https://github.com/sjimnar
theme:
  name: material
  logo: assets/images/logo.png
  features:
    - content.action.edit
    - blog.post.info
    - blog.tags
  palette: 
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  extra_css:
    - css/custom.css

plugins:
  - search
  - social
  - meta
  - blog:
      blog_dir: blog/
      tags_dir: tags/


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Home: index.md
  - Blog:
      - S3 Ransom Anatomy: blog/posts/s3-ransom-anatomy.md
      - S3 Ransomware Batch Deletion: blog/posts/s3-ransomware-batch-deletion.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sjnar/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/RYwhuSXx
    

  blog:
    post_date_format: '%Y-%m-%d'
